#!/bin/bash

#SBATCH --job-name=run_mummer4
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --mem=128g
#SBATCH --time=96:00:00
#SBATCH --output=/gpfs01/home/mzywj2/slurm-%x-%j.out
#SBATCH --error=/gpfs01/home/mzywj2/slurm-%x-%j.err
#######################
# PREPARE ENVIRONMENT #
#######################

# Load anaconda module and activate mummer environment
module load anaconda-uoneasy/2023.09-0
source ~/.bash_profile
conda activate mummer4_env

# Set input and output file paths
ASSEMBLY="/gpfs01/home/mzywj2/COFF001.asm.p_ctg.gfa.fasta" 
REFERENCE="/gpfs01/home/mzywj2/C_excelsa_V5.fa.masked.fa" 
OUTPUT_PREFIX="p_ctg_vs_excelsa"

# Run mummer4 on p_ctg
nucmer --mum -l 100 -c 500 --prefix $OUTPUT_PREFIX $REFERENCE $ASSEMBLY
