#!/bin/bash

#SBATCH --job-name=busco_c_exc
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --mem=128g
#SBATCH --time=96:00:00
#SBATCH --output=/gpfs01/home/mzywj2/slurm-%x-%j.out
#SBATCH --error=/gpfs01/home/mzywj2/slurm-%x-%j.err
#######################
# PREPARE ENVIRONMENT #
#######################

# Load anaconda module and activate busco environment
module load anaconda-uoneasy/2023.09-0
source ~/.bash_profile
conda activate busco_env

# Define input file, lineage dataset, and output directory
INPUT_FASTA="/gpfs01/home/mzywj2/C_excelsa_V5.fa.masked.fa"
LINEAGE="/gpfs01/home/mzywj2/busco_downloads/lineages/brassicales"
OUTPUT_DIR="/gpfs01/home/mzywj2/busco_output_cexc"

# Run busco command
busco \
-i $INPUT_FASTA \
-l $LINEAGE \
-o $OUTPUT_DIR \
-m genome

